version: '3'

services:
  nextcloud:
    image: nextcloud
    ports:
      - 8080:80
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=gorilla
      - MYSQL_PASSWORD=MaaGodt*7913
      - MYSQL_HOST=db
    volumes:
      - nextcloud:/var/www/html
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=gorilla
      - MYSQL_PASSWORD=MaaGodt*7913
      - MYSQL_ROOT_PASSWORD=MaaGodt*7913
    volumes:
      - db:/var/lib/mysql

volumes:
  nextcloud:
  db:
